name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install scikit-learn
          pip install matplotlib
          pip install seaborn
          pip install -r requirements.txt
          python train.py
          echo "MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md          
          cml comment feature_importance.png --md >> report.md
          cml comment residuals.png --md >> report.md
          cml comment create report.md
